#!/bin/sh
export DESKTOP_SESSION=2bwm
LOG=~/.cache/2bwm.log
savelog -c 7 $LOG || true
touch $LOG
exec 1>$LOG
exec 2>&1

echo "liftoff"
xrdb -merge ~/.Xresources

echo "autostart"
xsettingsd&
update-appcache.sh&
xsetroot -cursor_name left_ptr
dunst&
update-hsetroot.sh -r&
stalonetray&
sxhkd -c ~/.config/2bwm/sxhkd.conf &
st&

echo "idle"
exec xterm -geometry 200x10+0-0 -title xconsole -e tail -f $LOG
